[package]
name = "short-tailwind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.188", features = ["derive"]}
swc_common = "0.32.1"
swc_css_ast = "0.139.1"
swc_css_parser = "0.148.1"
