[package]
name = "short-tailwind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cssparser = "0.33.0"
html5ever = "0.26.0"
lightningcss = { version="1.0.0-alpha.47", features = ["visitor", "jsonschema"] }
parcel_selectors = { version="0.26.2"  }
serde = {version = "1.0.188", features = ["derive"]}
toml = "0.8.2"
